name: awesome_board
description: An App for creating climbing problems on moonboard sized Boards

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bottom_navy_bar: ^5.6.0
  cupertino_icons: ^1.0.0
  flutter_ble_lib: ^2.3.1

  flutter_launcher_icons: ^0.8.1
  fluttericon: ^1.0.7
  gradient_text: ^1.0.2
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  hive_generator: ^0.8.2
  http: ^0.12.2
  permission_handler: ^4.2.0+hotfix.3
  sqflite: null
  uuid: ^2.2.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/bouldertyp.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11

flutter:
  uses-material-design: true

  assets:
    - assets/database/moonboard_problems_setup_2016.json
    - assets/database/moonboardDB.sqlite
    - assets/images/
